# Generated by Django 2.2.7 on 2019-11-26 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OcProduct',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=64)),
                ('sku', models.CharField(max_length=64)),
                ('upc', models.CharField(max_length=12)),
                ('ean', models.CharField(max_length=14)),
                ('jan', models.CharField(max_length=13)),
                ('isbn', models.CharField(max_length=17)),
                ('mpn', models.CharField(max_length=64)),
                ('location', models.CharField(max_length=128)),
                ('quantity', models.IntegerField()),
                ('stock_status_id', models.IntegerField()),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('manufacturer_id', models.IntegerField()),
                ('shipping', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=4, max_digits=15)),
                ('points', models.IntegerField()),
                ('tax_class_id', models.IntegerField()),
                ('date_available', models.DateField()),
                ('weight', models.DecimalField(decimal_places=8, max_digits=15)),
                ('weight_class_id', models.IntegerField()),
                ('length', models.DecimalField(decimal_places=8, max_digits=15)),
                ('width', models.DecimalField(decimal_places=8, max_digits=15)),
                ('height', models.DecimalField(decimal_places=8, max_digits=15)),
                ('length_class_id', models.IntegerField()),
                ('subtract', models.IntegerField()),
                ('minimum', models.IntegerField()),
                ('sort_order', models.IntegerField()),
                ('status', models.IntegerField()),
                ('viewed', models.IntegerField()),
                ('date_added', models.DateTimeField()),
                ('date_modified', models.DateTimeField()),
                ('is_bespoke', models.IntegerField(blank=True, null=True)),
                ('bespoke_category', models.IntegerField(blank=True, null=True)),
                ('bespoke_template', models.IntegerField(blank=True, null=True)),
                ('include_google_merchant', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'oc_product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OcProductDescription',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('language_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('tag', models.TextField(blank=True, null=True)),
                ('meta_title', models.CharField(max_length=255)),
                ('meta_description', models.CharField(max_length=255)),
                ('meta_keyword', models.CharField(max_length=255)),
                ('long_description', models.CharField(max_length=2048)),
            ],
            options={
                'db_table': 'oc_product_description',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SsanSymbols',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('image_path', models.CharField(blank=True, max_length=255, null=True)),
                ('refenceno', models.CharField(blank=True, max_length=48, null=True)),
                ('referent', models.CharField(blank=True, max_length=255, null=True)),
                ('function', models.CharField(blank=True, max_length=1024, null=True)),
                ('content', models.CharField(blank=True, max_length=1024, null=True)),
                ('hazard', models.CharField(blank=True, max_length=1024, null=True)),
                ('humanbehav', models.CharField(blank=True, max_length=1024, null=True)),
                ('svg_path', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.IntegerField(blank=True, null=True)),
                ('standard_id', models.IntegerField(blank=True, null=True)),
                ('image_width', models.IntegerField(blank=True, null=True)),
                ('image_height', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ssan_symbols',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SsanProductSymbols',
            fields=[
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='products.OcProduct')),
            ],
            options={
                'db_table': 'ssan_product_symbols',
                'managed': False,
            },
        ),
    ]
