# Generated by Django 2.2.7 on 2019-12-09 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OcOrder',
        ),
    ]
